### ISSUE TITLE
web启动失败,URI格式化失败

### ISSUE THREAD

**Issue by Alanlxh** [chexagon/redis-session-manager#20]
25-Sep-2017 12:06:48.393 SEVERE [localhost-startStop-1] com.crimsonhexagon.rsm.RedisSessionManager.startInternal Unable to load serializer
 java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:6379
	at java.net.URI.create(URI.java:852)
	at org.redisson.misc.URIBuilder.create(URIBuilder.java:27)
	at org.redisson.config.SingleServerConfig.setAddress(SingleServerConfig.java:129)
	at com.crimsonhexagon.rsm.redisson.SingleServerSessionManager.configure(SingleServerSessionManager.java:20)
	at com.crimsonhexagon.rsm.redisson.BaseRedissonSessionManager.buildClient(BaseRedissonSessionManager.java:48)
	at com.crimsonhexagon.rsm.RedisSessionManager.startInternal(RedisSessionManager.java:130)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5224)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:988)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1860)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 127.0.0.1:6379
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.checkChar(URI.java:3031)
	at java.net.URI$Parser.parse(URI.java:3047)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 18 more

**Comment by scubasau** [comment]
It appears you have some non-printable illegal character in your configuration. Ensure your configuration matches `endpoint="127.0.0.1:6379"`

**Comment by markus7811** [comment]
We have the same error and double checked, that there is no unprintable character

**Comment by scubasau** [comment]
Apologies, it appears redisson changed the required URL format in 3.4.3:
https://github.com/redisson/redisson/blob/master/CHANGELOG.md#10-jun-2017---versions-293-and-343-released

I'll update the doc to reflect this change; you should use `endpoint="redis://127.0.0.1:6379"`

**Comment by scubasau** [comment]
Doc and default endpoint fixed in master.
