### ISSUE TITLE
NPE in catalina.out

### ISSUE THREAD

**Issue by cdx-grillo** [chexagon/redis-session-manager#25]
Hello,
I've been using redis-session-manager in production for about 3 months with good results.  Since we use AWS ElasticCache, I decided to try out the the config entries for AWS.   Here's a partial example of the NPE that repeats in catalina.out: 

10-Dec-2017 03:54:11.896 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 23281 ms
10-Dec-2017 03:54:47.766 FINE [http-nio-11443-exec-2] com.crimsonhexagon.rsm.RedisSessionManager.findSession Finding session 48DFDF3856B9C4806E38CD27A27E2656
10-Dec-2017 03:54:47.766 FINE [http-nio-11443-exec-2] com.crimsonhexagon.rsm.RedisSessionManager.findSession Loading from redis
10-Dec-2017 03:54:47.799 WARNING [redisson-netty-1-1] io.netty.util.concurrent.DefaultPromise.notifyListener0 An exception was thrown by org.redisson.command.CommandAsyncService$14.operationComplete()
 java.lang.NullPointerException
        at org.redisson.connection.pool.ConnectionPool.returnConnection(ConnectionPool.java:441)
        at org.redisson.connection.pool.SlaveConnectionPool.returnConnection(SlaveConnectionPool.java:30)
        at org.redisson.connection.balancer.LoadBalancerManager.returnConnection(LoadBalancerManager.java:210)

I'm using RSM version 2.2.1 and my context.xml config looks like this ... 
```<Manager className="com.crimsonhexagon.rsm.redisson.ElasticacheSessionManager"
              nodes="redis://my-redis-host-001-here:6379 redis://my-redis-host-002-here:6379 redis://my-redis-host-0030here:6379"
             nodePollInterval="1000"
             sessionKeyPrefix="_rsm_"
             saveOnChange="false"
             forceSaveAfterRequest="false"
             dirtyOnMutation="true"
             ignorePattern=".*\\.(ico|png|gif|jpg|jpeg|swf|css|js)$"
             maxSessionAttributeSize="-1"
             maxSessionSize="-1"
             allowOversizedSessions="false"
             masterConnectionPoolSize="100"
             slaveConnectionPoolSize="100"             
             database="0"
             timeout="60000"
             pingTimeout="1000"
             retryAttempts="20"
             retryInterval="1000"
    />```

Any assistance is greatly appreciated! 

Thanks,
Greg

**Comment by cdx-grillo** [comment]
Looks like this issue can be resolve with an upgrade to 3.5.6 of the redisson client (rsm currently set to use 3.5.1 redisson client in pom).  Will test and post if resolved.

**Comment by cdx-grillo** [comment]
when upgrading to redisson client 3.5.6, it caused a different set of errors.  However, an upgrade to redisson client 3.5.2 solved the issue.

**Comment by scubasau** [comment]
Hi, I've just released 2.2.1 which uses redisson 3.5.5. We've been using it in production for a couple weeks now with no issues. Give this a try and let me know if this fixes the issue.

**Comment by scubasau** [comment]
I'm also curious as to what the errors were with 3.5.6 if you remember (as this is an update we'll likely make in the near future)

**Comment by cdx-grillo** [comment]
Hello!  Sorry, I didn't keep the errors/stack trace but if you change the pom.xml to use redisson client v3.5.6, you should see the runtime errors immediately in catalina.out.  IIRC, it was a transient dependency on one of the libraries used by the redisson client versus a different version of the same library use in rsm.  

Interesting that v3.5.5 worked Ok, I _thought_ I tried that version as well and got the same error as v3.5.6 but I can't be certain about that.  FYI - I believe this error only surfaces when you use the AWS ElasticacheSessionManager.
