### ISSUE TITLE
Error after authentication. com.crimsonhexagon.rsm.RedisSessionManager.save Failed to save session. java.lang.IllegalArgumentException: java.io.NotSerializableException: az.grts.services.interbank.AuditRecord

### ISSUE THREAD

**Issue by ZulfuqarAliyev** [chexagon/redis-session-manager#30]
Hello. When I trie to authentificate my project, I got an error: 
SEVERE [http-nio-8080-exec-39] com.crimsonhexagon.rsm.RedisSessionManager.save Failed to save session [6EF8B47642C7728C55DB80BB3D839223]
 java.lang.IllegalArgumentException: java.io.NotSerializableException: az.grts.services.interbank.AuditRecord
	at org.redisson.RedissonObject.encode(RedissonObject.java:228)
	at org.redisson.RedissonBucket.setAsync(RedissonBucket.java:140)
	at org.redisson.RedissonBucket.set(RedissonBucket.java:131)
	at com.crimsonhexagon.rsm.redisson.RedissonSessionClient.save(RedissonSessionClient.java:46)
	at com.crimsonhexagon.rsm.RedisSessionManager.save(RedisSessionManager.java:309)
	at com.crimsonhexagon.rsm.RedisSessionManager.afterRequest(RedisSessionManager.java:343)
	at com.crimsonhexagon.rsm.RedisSessionRequestValve.invoke(RedisSessionRequestValve.java:88)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)

**Comment by mikebski** [comment]
Is `az.grts.services.interbank.AuditRecord` Serializable?  Post the class.

**Comment by ZulfuqarAliyev** [comment]
I made class serializable and everything is good now :)

**Comment by scubasau** [comment]
Thanks @mikebski !
