### ISSUE TITLE
 java.lang.NoSuchMethodError: com.crimsonhexagon.rsm.RedisSessionManager.getMaxInactiveInterval()

### ISSUE THREAD

**Issue by dmarko484** [chexagon/redis-session-manager#4]
Tried 2.0.4 and 2.0.5-snapshot but doesnt start in Tomcat 8.5.4 ... any idea what's wrong?

19-Aug-2016 14:39:14.653 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal The session manager failed to start
 org.apache.catalina.LifecycleException: Failed to start component [com.crimsonhexagon.rsm.redisson.SingleServerSessionManager[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5195)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: com.crimsonhexagon.rsm.RedisSessionManager.getMaxInactiveInterval()I
        at com.crimsonhexagon.rsm.RedisSessionManager.startInternal(RedisSessionManager.java:121)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
        ... 12 more

**Comment by scubasau** [comment]
I'm guessing tomcat 8.5.x added some additional parameters that need to be handled. This should be as simple as adding getters/setters.

**Comment by scubasau** [comment]
Closing old issues.
